ARG RELEASE=latest

FROM quay.io/fedora/fedora-toolbox:$RELEASE
LABEL authors="bhoy-troy"

ENV NAME=rhel-developer-toolbox

LABEL com.github.containers.toolbox="true" \
      com.redhat.component="$NAME" \
      name="$NAME" \
      version="$RELEASE" \
      summary="Container image for RHEL development built atop Fedora" \
      maintainer="James Troy <james@james-troy.com>"

RUN dnf --assumeyes install ansible cowsay

# Install Java (required for sonar-scanner), unzip, and wget
RUN dnf --assumeyes install java-17-openjdk-headless unzip wget

# Install sonar-scanner
RUN wget -q https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip && \
    unzip -q sonar-scanner-cli-5.0.1.3006-linux.zip && \
    mv sonar-scanner-5.0.1.3006-linux /opt/sonar-scanner && \
    ln -s /opt/sonar-scanner/bin/sonar-scanner /usr/local/bin/sonar-scanner && \
    rm sonar-scanner-cli-5.0.1.3006-linux.zip

# Install CodeClimate CLI
RUN wget -qO /usr/local/bin/codeclimate https://github.com/codeclimate/codeclimate/releases/download/v0.94.1/codeclimate-0.94.1-linux-amd64 && \
    chmod +x /usr/local/bin/codeclimate

# Enable repositories and extra tools

# NOTE(ianw) 2025-06 : it's unclear if this reamins supported; see discussion at
#  https://gitlab.com/redhat/rhel/tools/rhel-developer-toolbox/-/merge_requests/132#note_2505802571
# RUN dnf config-manager addrepo --from-repofile http://download.devel.redhat.com/beakerrepos/beaker-client-Fedora.repo



# This is a hack so that modern systems can build RHEL-8 kernel sources
RUN ln -s /usr/bin/python3 /usr/libexec/platform-python

# Install Ansible setup

COPY ansible /usr/share/rhel-dev-toolbox/ansible/

# Unfortunately gitlab CI seems to run with umask 000 so we get
# directories in the local checkout as 777 ... hence we need to
# cleanup permissions when copying directory hierarchies
RUN mkdir -p /usr/share/rhel-dev-toolbox/ansible && \
  chmod -R u+rwX,go+rX,go-w /usr/share/rhel-dev-toolbox
